all: test bench

.PHONY: test
test:
	go generate ./...
	go test -tags assert -v -timeout 30s ./...

.PHONY:
bench:
	go generate ./...
	go test -benchmem -run=^$ -bench=... -v -tags debug,assert ./...
