// Code generated by "stringer -type EventType internal/events/event_type.go"; DO NOT EDIT.

package events

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ErrorEventType - -2]
	_ = x[UnsupportedEventType - -1]
	_ = x[InterruptEventType-0]
	_ = x[ResizeEventType-1]
	_ = x[ClickEventType-2]
	_ = x[ScrollEventType-3]
	_ = x[KeyboardEventType-4]
}

const _EventType_name = "ErrorEventTypeUnsupportedEventTypeInterruptEventTypeResizeEventTypeClickEventTypeScrollEventTypeKeyboardEventType"

var _EventType_index = [...]uint8{0, 14, 34, 52, 67, 81, 96, 113}

func (i EventType) String() string {
	i -= -2
	if i < 0 || i >= EventType(len(_EventType_index)-1) {
		return "EventType(" + strconv.FormatInt(int64(i+-2), 10) + ")"
	}
	return _EventType_name[_EventType_index[i]:_EventType_index[i+1]]
}
