// This package contains multiple store for built-in Go types. Values are indexed in
// the store using an id.ID. Non Map stores id.ID must be generated by a registry
// before the creation of the store.

package store
