// Code generated by "stringer -type=PropID -trimprefix=PropID"; DO NOT EDIT.

package styles

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PropIDWidth-0]
	_ = x[PropIDMinWidth-1]
	_ = x[PropIDMaxWidth-2]
	_ = x[PropIDHeight-3]
	_ = x[PropIDMinHeight-4]
	_ = x[PropIDMaxHeight-5]
	_ = x[PropIDMarginLeft-6]
	_ = x[PropIDMarginTop-7]
	_ = x[PropIDMarginRight-8]
	_ = x[PropIDMarginBottom-9]
	_ = x[PropIDPaddingLeft-10]
	_ = x[PropIDPaddingTop-11]
	_ = x[PropIDPaddingRight-12]
	_ = x[PropIDPaddingBottom-13]
}

const _PropID_name = "WidthMinWidthMaxWidthHeightMinHeightMaxHeightMarginLeftMarginTopMarginRightMarginBottomPaddingLeftPaddingTopPaddingRightPaddingBottom"

var _PropID_index = [...]uint8{0, 5, 13, 21, 27, 36, 45, 55, 64, 75, 87, 98, 108, 120, 133}

func (i PropID) String() string {
	if i < 0 || i >= PropID(len(_PropID_index)-1) {
		return "PropID(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PropID_name[_PropID_index[i]:_PropID_index[i+1]]
}
