// Code generated by "stringer -type=ID -trimprefix=ID"; DO NOT EDIT.

package property

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[IDDisplay-1]
	_ = x[IDWidth-2]
	_ = x[IDMinWidth-3]
	_ = x[IDMaxWidth-4]
	_ = x[IDHeight-5]
	_ = x[IDMinHeight-6]
	_ = x[IDMaxHeight-7]
	_ = x[IDMarginLeft-8]
	_ = x[IDMarginTop-9]
	_ = x[IDMarginRight-10]
	_ = x[IDMarginBottom-11]
	_ = x[IDPaddingLeft-12]
	_ = x[IDPaddingTop-13]
	_ = x[IDPaddingRight-14]
	_ = x[IDPaddingBottom-15]
	_ = x[IDBackgroundColor-16]
	_ = x[unusedID-17]
}

const _ID_name = "DisplayWidthMinWidthMaxWidthHeightMinHeightMaxHeightMarginLeftMarginTopMarginRightMarginBottomPaddingLeftPaddingTopPaddingRightPaddingBottomBackgroundColorunusedID"

var _ID_index = [...]uint8{0, 7, 12, 20, 28, 34, 43, 52, 62, 71, 82, 94, 105, 115, 127, 140, 155, 163}

func (i ID) String() string {
	i -= 1
	if i < 0 || i >= ID(len(_ID_index)-1) {
		return "ID(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _ID_name[_ID_index[i]:_ID_index[i+1]]
}
